spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/briva_diena
    username: briva_diena_user
    password: briva_diena_password
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  uploads-path: ./uploads
